### ISSUE TITLE
Make the creation of FTelnetThread overridable

### ISSUE THREAD

**Issue by chuacw** [IndySockets/Indy#185]
It is not possible to override the creation and assignment of TIdTelnetReadThread to the FTelnetThread member of the TIdTelnet component.

Please allow overriding the creation and assignment of FTelnetThread for the following reasons:

1. In a console app, CheckSynchronize is not called, so FClient.Negotiate will not get called by the Synchronize(FClient.Negotiate) statement.

2. When overriding the TIdTelnet class, it's impossible to prevent FTelnetThread from getting assigned as well. Provide a Boolean property to decide whether to create TIdTelnetReadThread and assign it to FTelnetThread, or not.

3. TIdTelnetReadThread has a bug that causes it to get destroyed, which causes the entire TIdTelnet component to fail.

4. I have created an TIOSSHHandler that can transform the TIdTelnet component into a SSH client, however, the default creation of TIdTelnetReadThread to FTelnetThread is interferring with how my SSH client works, and duplicating the entire TIdTelnet component just to remove TIdTelnetReadThread from getting created is overkill, but necessary, until this gets fixed.

**Comment by rlebeau** [comment]
1. in environments where Synchronize() does not work by default (console, DLL, etc), set the TIdTelnet.ThreadedEvent property to false so Synchronize() is not used. Just make sure your event handlers are thread-safe.  Otherwise, move TIdTelnet to a worker thread, and then have the console app's main thread (or another worker thread) call CheckSynchronize() periodically.

2. This will not be changed.  TIdTelnetReadThread is core to TIdTelnet's design, so you can't prevent FTelnetThread from being created and assigned.  If you need a Telnet client that lets you do your own I/O reading, TIdTelnet is not the right component for you.  Use TIdTCPClient instead, and implement your own Telnet protocol handling.

3. The only time that FTelnetThread is destroyed is when the app calls TIdTelnet.Disconnect() (or TIdTelnet itself is destroyed).  Please provide specific details about the bug you think you have found.  What is actually happening?

4. It sounds like you may not have implemented your SSH handler correctly.  What exactly about FTelnetThread is interfering with your SSH implementation?  The thread runs independently of whatever type of IOHandler is assigned to TIdTelnet.  All the thread cares about is that the IOHandler is able to read/write bytes, it doesn't care how the IOHandler does it.  So, what is the actual issue you are having?  Again, please provide more specific details.  Your IOHandler must be implemented synchronously, and must fully establish its SSH session inside of an overridden TIdIOHandler.Open() or TIdIOHandlerSocket.ConnectClient() method.  Once the IOHandler's Open() method is called (which calls ConnectClient() internally if derived from TIdIOHandlerSocket), the IOHandler must be ready to handle I/O in both directions at any time.

**Comment by chuacw** [comment]
Thanks for your response, Remy.

I'll close this.
