### ISSUE TITLE
TIdServerIOHandlerSSLOpenSSL OnStatusInfoEx event failure

### ISSUE THREAD

**Issue by rayaswdelphidev** [IndySockets/Indy#216]
I have discovered the (IdSSLOpenSSL.pas) TIdServerIOHandlerSSLOpenSSL OnStatusInfoEx event will only fire once on the first connection then never for subsequent connections. The embarcadero web forums appear not to be working and I am trying to get some feedback regarding a fix I need implemented.

Tracing the Indy code I have found that SSL_accept() calls into the callback that was set by SSL_CTX_set_info_callback() that eventually lands into the OnStatusInfoEx event handler. It appears that TIdSSLSocket.Destroy is setting the callback to nil (too early?) which is preventing new connections after the first from triggering the OnStatusInfoEx event.

There is a "to do" note in the Indy code that seems to question if that is the right spot for resetting the callback to nil. I can't really gauge the volatility of moving/removing this code to a more appropriate spot so I have opted instead to try and make a fix to reset the callback at some more appropriate time until an official solution is available.

Simply resetting the callback with SSL_CTX_set_info_callback() just prior to SSL_accept() seems to work however I am hoping someone with Indy/SSL experience can help confirm this suggested fix would be a valid solution.

**Comment by rlebeau** [comment]
`SSL_CTX_...` APIs are handled at the context level, not the per-connection level.  A single CTX can be shared between multiple SSL objects, so it would not be a good idea to call `SSL_CTX_set_info_callback()` every time `SSL_accept()` is called. It should only be called when the CTX is initialized and destroyed (hence the TODO comment).

I really don't know why `SSL_CTX_set_info_callback()` is being called in `TIdSSLSocket.Destroy()`.  I don't know what the author was trying to solve by calling it there (I didn't write `IdSSLOpenSSL.pas` initially, I just maintain it).  Maybe the author meant to call `SSL_set_info_callback()` instead of `SSL_CTX_set_info_callback()`?  But the CTX info callback is called if an SSL-specific info callback is not assigned.

Maybe `TIdSSLSocket.Destroy()` should not be clearing the CTX callback at all, and Indy's `InfoCallback()` function should be ignoring events for SSL objects that are being destroyed.  I think that idea would be safer.

**Comment by rayaswdelphidev** [comment]
Thanks.  I will give it a try by reverting my changes and commenting the code in TIdSSLSocket.Destroy() that is causing the issue and see if any SSL messages popup during the destroy of the socket.  If no messages are generated perhaps I may not need to modify InfoCallback() at all.  InfoCallback() looks to be protected by a critical section but it's difficult for me to know if a message were during the destruction phase would cause a problem.  On the surface it doesn't seem obvious that it would.  

If I do need to modify InfoCallback() do you have any suggestions how to approach determining the destruction phase of the object to ignore calling StatusInfo()?  Perhaps via a simple field of TIdSSLSocket or via LHelper (IIdSSLOpenSSLCallbackHelper) callback interface?

Would you be interested in knowing the results if we proceed putting this fix into production?

**Comment by rayaswdelphidev** [comment]
I had created an item in Embarcadero's issue tracker.  Do you mind if I copy your comments there regarding this issue?
https://quality.embarcadero.com/browse/RSP-20786

**Comment by rlebeau** [comment]
You should not have created a ticket with Embarcadero.  This is not an Embarcadero issue, and they are just going to refer it back to me anyway.

**Comment by rayaswdelphidev** [comment]
Currently under some light stress testing (about 10-20 active threads at a time) we don't see any problems.  The the changes we made for this round of testing were only to remove the call to SSL_CTX_set_info_callback() from the destructor TIdSSLSocket.Destroy;  and add SSL_CTX_set_info_callback(fContext, nil) to procedure TIdSSLContext.DestroyContext; prior to the call to SSL_CTX_free().

**Comment by rlebeau** [comment]
> add SSL_CTX_set_info_callback(fContext, nil) to procedure TIdSSLContext.DestroyContext; prior to the call to SSL_CTX_free().

That should not be necessary.

**Comment by rayaswdelphidev** [comment]
In our beta environment with many users connected we have not encountered any errors so far.  However when making client side calls to HTTPS connections we noticed we started receiving a new message that we didn't notice before.  
From the StatusInfoEx event AType:
Handshake Start
Connect Loop (occurs many times)
Handshake Done
Connect Exit
warning Write Alert  <--- new message.

**Comment by rlebeau** [comment]
Hard to say without seeing the context in which that alert is being issued.  It could just be a normal alert sent while closing a connection, and could have been previously hidden by SSL_CTX_set_info_callback(nil) being called before closing the connection.  Your OnStatusInfoEx handler should be checking the AWhere, Aret, and  AType parameters to ignore callback events it is not interested in.

In any case, I have now checked in IdSSLOpenSSL.pas so that TIdSSLSocket.Destroy() no longer calls SSL_CTX_set_info_callback() before calling SSL_free() (SVN rev 5465).
