### ISSUE TITLE
Define IOHandlerSocketClass in TIdServerIOHandlerSSLOpenSSL for overriding creation of IOHandler

### ISSUE THREAD

**Issue by chuacw** [IndySockets/Indy#255]
Define IOHandlerSocketClass in TIdServerIOHandlerSSLOpenSSL so that in Accept, the creation of the IOHandler can be overridden to a descendant class.

Currently, in TIdServerIOHandlerSSLOpenSSL.Accept, the creation of the IOHandler is as follows:

`  LIO := TIdSSLIOHandlerSocketOpenSSL.Create(nil);
`
which means it cannot be overridden.

By defining IOHandlerSocketClass, and changing the IOHandler creation to 

`  LIO := IOHandlerSocketClass.Create(nil);
`
this allows the IOHandler to be overridden to a descendant.

**Comment by rlebeau** [comment]
By its very name, TIdServerIOHandlerSSLOpenSSL is specific to OpenSSL, and so it creates instances of TIdSSLIOHandlerSocketOpenSSL. This is by design, and your proposal breaks that design. If you want to use a custom TIdIOHandler class for the clients of Indy TCP servers, you are expected to create a custom TIdServerIOHandler-derived class that overrides Accept() to create instances of your custom IOHandler.

**Comment by chuacw** [comment]
I'm conforming to the design.
My proposal is for

IOHandlerSocketClass to be defined as taking a type = class of TIdSSLIOHandlerSocketOpenSSL

so that TIdServerIOHandlerSSLOpenSSL.Accept can create a descendant TIdSSLIOHandlerSocketOpenSSL class.

**Comment by rlebeau** [comment]
I thank you for your proposal, but I see no real benefit to implementing it. If you write a custom descendant of TIdSSLIOHandlerSocketOpenSSL, it takes only a few extra lines of code to write a custom descendant of TIdServerIOHandlerSSLOpenSSL to go with it.  You have to manually assign the TIdTCPServer.IOHandler property in order to use TIdServerIOHandlerSSLOpenSSL anyway, so you can just as easily do the same with a descendant.
