### ISSUE TITLE
Enable the non-blocking code in TIdStackVCLPosix.SetBlocking

### ISSUE THREAD

**Issue by chuacw** [IndySockets/Indy#256]
According to [SOCKET(2), Linux Programmer's Manual](http://man7.org/linux/man-pages/man2/socket.2.html), it's possible for a socket to be non-blocking.

However, the current code in TIdStackVCLPosix.SetBlocking is commented out, and raises an immediate exception if the parameter ABlocking is set to false.

This issue suggests for the current commented code in TIdStackVCLPosix.SetBlocking to be uncommented and for the check on "if not ABlocking" to be removed.

**Comment by rlebeau** [comment]
The main reasons why non-blocking mode is currently not allowed to be enabled is because:

1. Indy is designed around the use of blocking sockets, and the majority of operations would simply not work correctly in non-blocking mode (and yes, I'm aware that TIdStackWindows does allow non-blocking mode to be enabled).

2. I'm not a 'Nix developer and don't know if the commented out code will compile as-is or not.

That being said, I have already been considering what you propose for a long awhile now, if for no other reason than I want to use it in TIdIOHandlerStack.ConnectClient() to implement the ConnectTimeout feature without using a worker thread anymore.

Though, note that there is also code in TIdStackVCLPosix.WouldBlock() that would need to be uncommented as well, and TIdStackVCLPosix.WSSocket() should be updated to apply the SOCK_NONBLOCK flag when the AOverlapped parameter is true.  And all of these changes would also have to be applied to TIdStackUnix, TIdStackLinux, and TIdStackLibc as well to accommodate FreePascal, as TIdStackVCLPosix is used only in Delphi/C++Builder.

**Comment by chuacw** [comment]
Remy,

Thanks for sharing the changes involved.

I've actually used the code from the commented out block, and that works.
I've also tested the O_NONBLOCK parameter when creating a socket, and that works too.

**Comment by rlebeau** [comment]
Enabling non-blocking mode has now been implemented for all of the `TIdStack` descendant classes.

**Comment by chuacw** [comment]
Thanks, Remy!
