### ISSUE TITLE
Missing Packages

### ISSUE THREAD

**Issue by vincentparrett** [IndySockets/Indy#280]
I'm looking at creating [DPM](https://github.com/DelphiPackageManager/DPM)  packages for Indy (using it as my testbed for design time package support in dpm) and noticed there are no dpk/dproj files for XE5  or later. 

I see there is a restructure branch (WIP?) and some issues that mention the use of libsuffix (#133, #134 ) - is there a plan for this work or would a PR be accepted? I might be willing to work on it.

**Comment by rlebeau** [comment]
Indy has run-time and design-time DPKs for Delphi up to 10.2 Tokyo (I haven't created DPKs for 10.3 Rio yet). There are few project groups in the main \Lib folder, but there are individual DPKs in the \Lib\System, \Lib\Core, and \Lib\Protocols subfolders.

The Restructure branch (yes, a work in progress) will eventually become Indy 11. Part of that effort includes renaming the DPKs and making them use {$LIBSUFFIX}. What is currently checked in to that branch is not up to date, though. I have new code I haven't checked in yet. It is an effort I can't finalize by myself right now as I don't have a working IDE due to a computer failure I experienced awhile back ago and haven't really recovered from yet.

**Comment by vincentparrett** [comment]
I must be missing something, I don't see any packages > IndyXXX250.dpk ? or are you talking about the restructure branch? 

BTW the Lib folder is superfluous, just adds more depth to the search paths. Not sure what else you plan to put in the repo, but Source and Packages could be at the root level.

**Comment by rlebeau** [comment]
As I said, I have not yet created any package files for 10.3. Rio (package version 260), but there are files for 10.2 Tokyo (package version 250) and earlier.

In the **master** branch, there are `IndyXXX250.dpk` files (and earlier) in the `\Lib\System`, `\Lib\Core`, and `\Lib\Protocols` folders, and `dclIndyXXX250.dpk` files (and earlier) in the `\Lib\Core` and `\Lib\Protocols` folders.

In the **Restructure** branch, the same files (without the package version numbers in their names) are in the `\Lib\Packages\RADStudio_10_2_Tokyo` and earlier folders.

The `\Lib` folder is not superfluous.  It is there it keep the source code separate from everything else that Indy has (package builder, test suites, etc).  They just haven't been added to the Restructure branch yet.  I will not be moving the `\Source` and `\Packages` folders up higher in the folder hierarchy, they are intended to stay in the `\Lib` folder.

**Comment by vincentparrett** [comment]
Ah my bad, I forgot about the stupid differences between compiler versions and package versions etc.. gets confusing- I was reading 250 and thinking XE4.

**Comment by rlebeau** [comment]
See [Compiler Versions](http://docwiki.embarcadero.com/RADStudio/en/Compiler_Versions) on Embarcadero's DocWiki, it documents which Package version number belong to which Compiler version.
