### ISSUE TITLE
Missing BPL package to install in Cpp Builder

### ISSUE THREAD

**Issue by emilianoveiga** [IndySockets/Indy#308]
After compile master branch to install in Cpp Builder 10 Seattle, the generated folder no contains  .BPL package to install Indy.

thus, commenting "del" lines on Fullc_Seattle.bat, the design packages .bpl are available in C23 folder to install in IDE.

**Comment by emilianoveiga** [comment]
By commeting "del" lines on Fullc_Seattle.bat, the design packages .bpl are available in C23 folder to install in IDE. That's ok, I got Indy running, but the version keep showing 10.6.2 and when using TIdHttpClient and IdSSLIOHandlerSocketOpenSSL to connect and download file in https:// address, I got the exception error: 

First chance exception at $74DB4402. Exception class EIdOSSLUnderlyingCryptoError with message
'Error connecting with SSL.
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'.

This is the same exception that occurs in original version that cames with Cpp 10 Seattle, ie, in Indy 10 build 5311.

If you can give some advice in order to solve this issue, I'll be greatful.

Best regards

**Comment by rlebeau** [comment]
This is three separate and unrelated issues.  This is not a discussion forum.  Please re-submit these issues as separate tickets.

Regarding the version number in IdVers.inc, this is a known issue, see https://github.com/IndySockets/Indy/issues/292.

**Comment by rlebeau** [comment]
`Fullc_Seattle.bat` compiles `.BPL` files into the `%BDSCOMMONDIR%\Bpl\` folder first, and then moves them into the `C23\Win32\Release` folder.  There are no `del` commands that reach into that folder, so the `.BPL` files should still be there.

**Comment by emilianoveiga** [comment]
I certified that %BDSCOMMONDIR% is correct path and runned .bat script. The C23 folder is created with .hpp, .bpi, .lib and .res files, but without .BPL packet install file.

The .bat script performs :
copy "%BDSCOMMONDIR%\Bpl\*Indy*.bpl" %IndyPlatform%\%IndyConfig%

But, there is *Indy* BPL file in BDSCOMMONDIR/Bpl

after copy, del commands where performed and C23 folder stay only with Win32 folder. BPLs files are missing. The quick workaround was disable del commands and BPL file, incluind .dcu and .res keep available in folder.

**Comment by rlebeau** [comment]
> I certified that %BDSCOMMONDIR% is a correct path. So runned .bat script. The C23 folder is created with .hpp, .bpi, .lib and .res files, but without .BPL package install file.

Did you verify that the `.BPL` files are being created in the `%BDSCOMMONDIR%\Bpl` folder BEFORE the `.BAT` script tries to touch them?

> The .bat script performs :
> copy "%BDSCOMMONDIR%\Bpl*Indy*.bpl" %IndyPlatform%%IndyConfig%

Exactly (BTW, the above is missing `\` between `\Bpl` and `*Indy*.bpl`, and between `%IndyPlatform%` and `%IndyConfig%`.  Those `\` are actually in the `.BAT` file).  Did you verify the `copy` is successful before any`del` commands are called?

> But, there is no `*Indy*` BPL file in `%BDSCOMMONDIR%/Bpl`

By the time the `.BAT` script is done running, yes, because it deletes them after copying them:

```
copy "%BDSCOMMONDIR%\Bpl\*Indy*.bpl" %IndyPlatform%\%IndyConfig%
del /Q "%BDSCOMMONDIR%\Bpl\*Indy*.bpl"
```

> The quick workaround was disable DEL commands from .bat script and BPL file, incluind .dcu and .res keep available in folder.

I understand that, but that doesn't explain WHY the `DEL` commands are deleting things they should not be deleting.  The only thing I can think of is if maybe the `del /Q *.*` command inside the `C23` folder is deleting recursively, which it shouldn't be.  And that would have also deleted files that you said are actually present once the `.BAT` script is finished.   There are only 3 commands in the `.BAT` file that could possibly be touching the `.BPL` files after they are compiled:

```
cd ..\..\C23
...
copy "%BDSCOMMONDIR%\Bpl\*Indy*.bpl" %IndyPlatform%\%IndyConfig%
...
del /Q "%BDSCOMMONDIR%\Bpl\*Indy*.bpl"
...
del /Q *.*
```

None of those commands should be causing the behavior your describe.  So, can you please step through the `.BAT` script line-by-line (put `pause` after each one, if you need to) and verify EXACTLY which command is preventing the `.BPL` files from reaching, or being left in, the destination folder correctly?

**Comment by emilianoveiga** [comment]
Ok, thanks! I'll do it and update this issue.

**Comment by emilianoveiga** [comment]
I've performed new test using step through the .BAT script line-by-line by using pause after each one. /* Fullc_Seattle.bat; C23 build version */

> Did you verify that the .BPL files are being created in the %BDSCOMMONDIR%\Bpl folder BEFORE the .BAT script tries to touch them?

Yes, the BPL files isn't created in the %BDSCOMMONDIR%\Bpl. They are created in \%IndyPlatform% folder.

> Exactly (BTW, the above is missing \ between \Bpl and *Indy*.bpl, and between %IndyPlatform% and %IndyConfig%. Those \ are actually in the .BAT file). Did you verify the copy is successful before anydel commands are called?

The copy command tried to perform:
copy "%BDSCOMMONDIR%\Bpl\*Indy*.bpl" %IndyPlatform%\%IndyConfig%
But, there is no *Indy*.bpl file there.

The command should copy *Indy*.bpl from \%IndyPlatform%, because .BPL files is there.

> The only thing I can think of is if maybe the del /Q *.* command inside the \%IndyPlatform%  folder is deleting recursively, which it shouldn't be...

**Yes, you're right. Shouldn't be, but after del /Q *.* all files at %IndyPlatform% including .BPL files was removed.** The remaining files, ie, .BPI, .LIB, .HPP and .RES still at %IndyPlatform%\%IndyConfig%

So, as commands are coping all generated files to %IndyPlatform%\%IndyConfig% it should include coping the .BPL files at %IndyPlatform% to %IndyConfig%.
