### ISSUE TITLE
ProcessPath function lead to directory traversal exploit

### ISSUE THREAD

**Issue by D3lphi3r** [IndySockets/Indy#312]
See in the below code:
```
  if SameText(ARequestInfo.Command, 'GET') then begin
    if TextStartsWith(ARequestInfo.Document, '/') then
    begin
      FileName := Copy(ARequestInfo.Document, 2, MaxInt);

      if FileName = '' then
        FileName := 'index.html';

      FileName := ProcessPath('C:\html', FileName);

      if FileExists(FileName) then
      begin
        AResponseInfo.ResponseNo    := 200;
        AResponseInfo.ContentStream := TFileStream.Create(FileName, fmOpenRead or fmShareDenyWrite);
        AResponseInfo.ContentType   := MIMETable.GetFileMIMEType(FileName);
        Exit;
      end
      else
      AResponseInfo.ResponseNo   := 404;
    end;
  end;
```

Requesting this URL : http://HOST/windows/win.ini
Gives 404
FileName: C:\html/windows/win.ini
Reponse: Empty

Requesting this URL : http://HOST//windows/win.ini Note the double //
Gives 200
FileName: /windows/win.ini
Reponse: content of C:\Windows\win.ini

I solve this by adding this

```
      FileName := Copy(ARequestInfo.Document, 2, MaxInt);

      if TextStartsWith(FileName, '/') then
      repeat
        FileName := Copy(FileName, 2, MaxInt);
      until NOT TextStartsWith(FileName, '/');

      if FileName = '' then
        FileName := 'index.html';
```

**Comment by rlebeau** [comment]
You are misusing `ProcessPath()`.  It is not intended to be used with path components that mix forward slashes with backslashes.  Your proposed solution alters the semantics of the path you are receiving from the URL, since the `//` would be part of the requested path and the trailing `/` should not be striped off when merged with your base path.

You need to change `'C:\html'` to `'C:/html'` when calling `ProcessPath()`, since HTTP paths use `/` only.  Then the result will be `C:/html/windows/win.ini`, which Windows APIs (that `FileExists()` and `TFileStream` use internally) will handle that path just fine as-is.  Or, you can choose to normalize the final path to `C:\html\windows\win.ini` before using it.
