### ISSUE TITLE
TLS - Problems with https://testesmoleculares.com.br/ on Cloudflare

### ISSUE THREAD

**Issue by wellington1993** [IndySockets/Indy#317]
I'm not have expertise with Delphi and TLS using Indy. Maybe it's not a problem, just config.

Page: https://testesmoleculares.com.br/
Error:
```
---------------------------
Debugger Exception Notification
---------------------------
Project IntegradorApoiado.exe raised exception class EIdOSSLUnderlyingCryptoError with message 'Error connecting with SSL.
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'.
---------------------------
Break   Continue   Help   
---------------------------
````

Actual config:
```
LHandler.SSLOptions.Method := sslvSSLv2;
LHandler.SSLOptions.Mode := sslmClient;
LHandler.SSLOptions.SSLVersions := [sslvSSLv2];
```

Tried:
```
IdSSLIOHandlerSocketOpenSSL1.SSLOptions.Method := sslvTLSv1_2;
IdSSLIOHandlerSocketOpenSSL1.SSLOptions.SSLVersions := [sslvTLSv1_2];
```

Someone can help?
Maybe providing an example of POST? I'm using Delphi XE4

Thanks!

**Comment by wellington1993** [comment]
Stackoverflow question:
https://stackoverflow.com/questions/63081968/deplhi-with-indy-and-tls-problems-with-https-testesmoleculares-com-br-cloud

**Comment by rlebeau** [comment]
(copied from my answer on StackOverflow)

Without seeing the actual handshake data, it is difficult to say for sure why it is failing.

However, I will mention that `sslvSSLv2` is for SSL v2.0, which *nobody* uses anymore, as it is no longer secure.  Same with `sslvSSLv3` (SSL v3.0).  So, never use `sslvSSLv2` and `sslvSSLv3` (unless you HAVE to, for legacy purposes).

`sslvTLSv1_2` is for TLS v1.2.  A lot of servers are now migrating to this.  But many servers haven't fully migrated yet.  So, you should enable TLS v1.0 and v1.1 as well for wider acceptance, eg (do not use `SSLOptions.Method` at all, just use `SSLOptions.SSLVersions`):

```delphi
LHandler.SSLOptions.Mode := sslmClient;
LHandler.SSLOptions.SSLVersions := [sslvTLSv1, sslvTLSv1_1, sslvTLSv1_2];
```

By specifying multiple TLS versions, that will allow OpenSSL to negotiate an available version that both peers support.

Also, make sure you are using an up-to-date version of Indy (if you are not already) so that you have all of its fixes for TLS support, such as use of SNI (which many servers now require TLS clients to use).

I can connect to `https://testesmoleculares.com.br/` in a web browser using TLS 1.2, so it should be possible to connect to it using TLS 1.2 in Indy as well.

**Comment by wellington1993** [comment]
@rlebeau Thanks for the fast response. I will try, make sense for me.

I think we are using old Indy version. Sorry for the question, but how to check or update the Indy version?
I'm new in the Delphi world and I have some doubts in that journey. 

Thanks again!

**Comment by rlebeau** [comment]
To see the version used, all Indy components have a public `Version` property you can query at run-time, or you can right-click on any Indy component in the IDE's Form Designer at design-time.  To update, see Indy's [installation instructions](http://ww2.indyproject.org/Sockets/Docs/Indy10Installation.EN.aspx).

**Comment by wellington1993** [comment]
Hi @rlebeau

My friend @hotsoft-develop7(Francisco) tried if this configuration works:

```pascal
LHandler.SSLOptions.Mode: = sslmClient;
LHandler.SSLOptions.SSLVersions: = [sslvTLSv1, sslvTLSv1_1, sslvTLSv1_2];
```

But it's still not working. He checked and Indy is updated.
I asked for the error and more details. I'll share it here when he answers me.

Thank you!

**Comment by wellington1993** [comment]
@rlebeau We have the same error after change the settings as suggested.

Do you have other ideas?
Could you provide a simple Indy example with that server as destination to help us?

Thanks in a lot!

**Comment by rlebeau** [comment]
What is the actual Indy version number you are using?

There is no other code to provide.  What I have already given you should be working, provided everything is updated and configured properly.

There is really no way I can diagnose this without seeing the actual TLS handshake data.  Please capture the handshake from both Indy and a working web browser, and then we can compare them for any differences.  You can use Wireshark for that capture.

Also, what kind of details are you getting from `TIdSSLIOHandlerSocketOpenSSL` itself?  Please attach an `OnStatusInfo/Ex` event handler to it and provide the output.

**Comment by wellington1993** [comment]
Hi @rlebeau, Thanks for the reply.

@hotsoft-desevn7(Francisco) said already tried all combinations and all generates the same error.
I will search for how to do the "OnStatusInfo/Ex event" thing.

He tried:
```pascal
LHandler.SSLOptions.Method := sslvTLSv1;
LHandler.SSLOptions.SSLVersions := [sslvTLSv1_2, sslvTLSv1_1, sslvTLSv1];

LHandler.SSLOptions.Method := sslvSSLv3;
LHandler.SSLOptions.SSLVersions := [sslvSSLv2, sslvSSLv23, sslvSSLv3];

LHandler.SSLOptions.Method := sslvTLSv1_2;
LHandler.SSLOptions.SSLVersions := [sslvSSLv2, sslvSSLv23, sslvSSLv3];
```

O know some combinations is not correct, but he said tried many combinations.
He said get the same error all the time in every combination.

Could you said more about?

> Also, what kind of details are you getting from TIdSSLIOHandlerSocketOpenSSL itself? Please attach an OnStatusInfo/Ex event handler to it and provide the output.

Indy version: 10.6.0.4975

Thanks!

**Comment by rlebeau** [comment]
> Indy version: 10.6.0.4975

That is a VERY OLD version of Indy.  No wonder why you are having so many troubles.  You need to upgrade in order to use TLS 1.2 properly.  The latest version is 10.6.2.

https://github.com/IndySockets/Indy/

http://ww2.indyproject.org/Sockets/Docs/Indy10Installation.EN.aspx

And BTW, you really need to stop using the `SSLOptions.Method` to specify the TLS version.  Use only the `SSLOptions.TLSVersions` property.  The two properties are mutually exclusive, setting one updates the other.  Pretend that the `SSLOptions.Method` property doesn't exist, as it is a deprecated property.

**Comment by wellington1993** [comment]
I sent all instructions to @hotsoft-desenv7, waiting for he response.
The "SSLOptions.TLSVersions" usage suggestion are interesting.

Thanks! @rlebeau

**Comment by wellington1993** [comment]
We can't find "TLSVersions"...

Could you provide a complete GET/POST example, from the component create to the request and TLS config?
And maybe with events interception...

Thanks! @rlebeau

**Comment by wellington1993** [comment]
We still have the same problems after Imdy update 😢 @rlebeau

**Comment by rlebeau** [comment]
> We can't find "TLSVersions"...

Sorry, I meant `SSLVersions`.

> Could you provide a complete GET/POST example, from the component create to the request and TLS config?

Something like this:

```
uses
  ..., IdHTTP, IdSSLOpenSSL;

var
  HTTP: TIdHTTP;
  SSL: TIdSSLIOHandlerSocketOpenSSL;
  Response: string;
begin
  HTTP := TIdHTTP.Create;
  try
    SSL := TIdSSLIOHandlerSocketOpenSSL.Create(HTTP);
    SSL.SSLOptions.Mode := sslmClient;
    SSL.SSLOptions.SSLVersions := [sslvTLSv1, sslvTLSv1_1, sslvTLSv1_2];
    // other SSL/TLS settings as needed...
    HTTP.IOHandler := SSL;

    Response := HTTP.Get('https://testesmoleculares.com.br/');
    // Or HTTP.Post(), as needed...
  finally
    HTTP.Free;
  end;

  // use Response as needed...
end;
```

**Comment by wellington1993** [comment]
Hi @rlebeau 

I will check with Francisco(@hotsoft-desenv7) if that example helped us.

Thanks!

**Comment by wellington1993** [comment]
Thanks @rlebeau !

Working now @rlebeau with your help! 

Francisco(@hotsoft-desenv7) used something like that:
```pascal
http := TidHTTP.Create(nil); //MainData.GetHTTP;
LHandler := TIdSSLIOHandlerSocketOpenSSL.Create(http);
LHandler.SSLOptions.Mode := sslmClient;
LHandler.SSLOptions.SSLVersions := [sslvTLSv1, sslvTLSv1_1, sslvTLSv1_2];
http.IOHandler := LHandler;
http.AllowCookies := True;
http.Request.Accept := 'text/html, */*';
http.Request.UserAgent := 'Mozilla/4.0';
http.Request.ContentType := 'text/plain; charset=utf-8';
http.HandleRedirects := True;
http.ProtocolVersion := pv1_1;
http.Request.Connection := 'keep-alive';
http.ReadTimeout := 30000;
http.ConnectTimeout := 30000;
```

Thanks!
