### ISSUE TITLE
How to capture an SMTP error on EHLO ?

### ISSUE THREAD

**Issue by tothpaul** [IndySockets/Indy#318]
Hello,

I have an SMTP server that is broken somehow, I use a valid certificate to send an email, but after the TLS handcheck, TidSMTP sends a EHLO message and the server response is "421 4.7.1 SSL certificate error"...I'de like to capture this error, but TidSTMP just sends an HELO message because the response is not 250, and I fall on a read timeout.

this is a server bug, but I'de like to have the SSL certificat error instead of a read timeout.

How can I do that ?

Thanks

**Comment by rlebeau** [comment]
Since `TIdSMTP` does not treat a `EHLO` error reply as a failure, the only way I can see to capture the `EHLO` response is to either:

1. assign a `TIdConnectionIntercept`-derived component to the `TIdSMTP.Intercept` property, such as one of the `TIdLog...` components, which will be called for all outgoing SMTP commands and incoming SMTP responses.

2. derive a new class from `TIdSMTP` and override the virtual `GetResponse()`, `GetInternalResponse()`, or `CheckResponse()` method.  For `GetResponse()` and `GetInternalResponse()`, call the `inherited` method first to actually read the response from the socket.  In all three cases, you can then get the details of the response from the `TIdSMTP.LastCmdResult` property.  If you are interested only in `EHLO`, you could also override the virtual `PrepareCmd()` method to know when `EHLO` is being sent so you can set a flag for your `(Get|Getinternal|Check)Response()` override to look for.

**Comment by rlebeau** [comment]
TODO: add an `OnFailedEHLO` event so the user can capture an `EHLO` failure w/ details, and decide whether to continue with `HELO` or end the session with `QUIT`.
