### ISSUE TITLE
idHTTPProxyServer commandCONNECT traffic hangs

### ISSUE THREAD

**Issue by eichgee** [IndySockets/Indy#341]
Hello,
I'm trying to use this component for SSH client/tunneling
I did notice when traffic CONNECT comes this component doesn't handle it well

I came across to the code and find out that this problem get fixed by commenting idSocketlist.SelectReadList
and the traffic becomes faster and stable, but another problem is the cpu usage gets high when i disable this code
so i doubt it this is the correct way to fix that

is there a better way to fix this?

```
procedure TIdHTTPProxyServer.CommandCONNECT(ASender: TIdCommand);
  ...
begin
  ...
              while LContext.Connection.Connected and  LContext.FOutboundClient.Connected do begin

                // if LReadList.SelectReadList(LDataAvailList, IdTimeoutInfinite)  << this makes traffic hangs
                // then
                // begin
                
                  if LDataAvailList.ContainsSocket(LConnectionHandle) then
                  begin
                    LContext.Connection.IOHandler.CheckForDataOnSource(0);
                  end;
                  if LDataAvailList.ContainsSocket(LOutBoundHandle) then
                  begin
                    LContext.FOutboundClient.IOHandler.CheckForDataOnSource(0);
                  end;

                  if not LContext.Connection.IOHandler.InputBufferIsEmpty then
                  begin
                    LContext.Connection.IOHandler.InputBuffer.ExtractToStream(LClientToServerStream);
                  end;
                  if not LContext.FOutboundClient.IOHandler.InputBufferIsEmpty then
                  begin
                    LContext.FOutboundClient.IOHandler.InputBuffer.ExtractToStream(LServerToClientStream);
                  end;

                // end;
...
end;
```

**Comment by rlebeau** [comment]
By disabling the call to `LReadList.SelectReadList()`, `LDataAvailList` won't be updated on each loop iteration, thus `LDataAvailList.ContainsSocket()` will always return False for both sockets, and the calling thread will never be put to sleep while waiting for new data but instead will run an unyielding loop that continuously polls both sockets for data, which is why you see the high CPU usage.

`LReadList.SelectReadList()` waits for new data to arrive on either socket.  If it is hanging, then there is no data arriving on both sockets.  My guess would be that the earlier `Connected` calls are reading the data instead (as they internally perform reads with 0-millisecond timeouts), thus not leaving behind anything new for `LReadList.SelectReadList()` to read.

So, I can think of a few different ways to address this:

- disable the `Connected` calls on the loop:

    `while True{LContext.Connection.Connected and LContext.FOutboundClient.Connected} do`

  And update the loop iterations to call `IOHandler.CheckForDisconnect()` on each socket.

- re-write the loop to not use `LReadList.SelectReadList()` at all, or at least to update `LReadList` dynamically on each loop iteration depending on whether each `Connected` read any data or not.

- put a small timeout on `LReadList.SelectReadList()`, and move the `if not IOHandler.InputBufferIsEmpty then InputBuffer.ExtractToStream()` blocks outside of the `if LReadList.SelectReadList()` block.

Will have to experiment with different things to see what works best.

**Comment by eichgee** [comment]
thank you for your explanation and clues
