### ISSUE TITLE
EIdOSSLConnectError Error connecting with SSL - EOF was observed

### ISSUE THREAD

**Issue by thomsentaastrup** [IndySockets/Indy#345]
We have just moved one of our applications from a Windows Server 2012 to a Windows Server 2019 and are receiving the error: EIdOSSLConnectError Error connecting with SSL - EOF was observed, on the first attempt to connect on a TIdTCPClient. Second attempt and onwards is working fine. Restarting application results in one error and the success again.

We are using Delphi 10.2, Indy 10.6.2.5366

Here is the relevant part of the code

  TCPClientCC := TIdTCPClient.Create(nil);
  TCPClientCC.ConnectTimeout := 1000;
  TCPClientCC.ReadTimeout := 1000;
  TCPClientCC.CreateIOHandler(TIdIOHandlerStack);
  TCPClientCC.OnStatus := TCPClientCCStatus;

  TCPClientCC.Port := Port;
  TCPClientCC.Host := Host;
    
  IOH := TIdSSLIOHandlerSocketOpenSSL.Create;
  IOH.SSLOptions.Method := sslvTLSv1_2;
  IOH.SSLOptions.Mode := sslmClient;
  IOH.SSLOptions.RootCertFile := 'ICProduct_CertChain.pem';
  IOH.SSLOptions.CertFile := 'IC_Client_.pem';
  IOH.SSLOptions.KeyFile := 'IC_Client_pvk.pem';
  IOH.OnGetPassword := GetClientPassword;
  IOH.OnStatusInfo := ClientCCStatusInfo;
  TCPClientCC.IOHandler := IOH;

  TCPClientCC.Connect;

Any suggestions?

**Comment by rlebeau** [comment]
An EOF error means the server is closing its end of the TCP connection during the TLS handshake.  You need to find out why.  Most likely, the server does not like something in your client's TLS hello, so it just kicks the client out abruptly.  I can't tell you what that something could be without more details.  Are you writing the server, too?  Have you tried sniffing the TLS handshake with Wireshark to see if there are any problems with it? Is the IOHandler's `OnStatusInfo` event giving you any details?  Have you tried looking at the output of the IOHandler's `OnStatusInfoEx` event?

Also, why is your client code calling `CreateIOHandler()`?  It should not be calling that method at all, since you are assigning the `IOHandler` property manually afterwards.  Otherwise, if you want to use `CreateIOHandler()`, then you need to get rid of the manual `IOHandler` assignment altogether, use `CreateIOHandler(TIdSSLIOHandlerSocketBase)` instead, and then type-cast the `IOHandler` property to `TIdSSLIOHandlerSocketOpenSSL` to assign its sub-properties as needed.
