### ISSUE TITLE
After update 10.6.2.3662 -> 10.6.2.3801 [FPC3.2.0] - Could not load SSL library. [only macOS11]

### ISSUE THREAD

**Issue by jonyrh** [IndySockets/Indy#346]
After update 10.6.2.3662 -> 10.6.2.3801 in Lazarus 2.0.12 + FPC 3.2.0, macOS 11, LibreSSL 2.8.3

Not work any more:
```
IdOpenSSLSetLoadSymLinksFirst(False);
```
Error: Could not load SSL library.

In Ununtu + libssl 1.0.2 working normal.

**Comment by rlebeau** [comment]
What does Indy's `WhichFailedToLoad()` function report after the error occurs?

Note that Indy does not officially support LibreSSL (see https://github.com/IndySockets/Indy/issues/231), however no changes have been made to Indy recently that should have broken what was previously working for LibreSSL, so I'm assuming this is actually a LibreSSL/macOS issue rather than an Indy issue.

Are you sure that LibreSSL 2.8.3 is backwards compatible with OpenSSL 1.0.2?  Are you sure you are actually using LibreSSL 2.8.3?  The current version of LibreSSL is 3.3.3.

**Comment by jonyrh** [comment]
Hello, rlebeau!

Yes, I use last macOS 11:
![image](https://user-images.githubusercontent.com/28771126/121120066-47017880-c836-11eb-8255-41bfa6576849.png)

This ploblen only in new version Indy 10.6.2.3801.
If compile project with preveus version 10.6.2.3662 - all is good!

Simle code from my project:
```
if FileExists(aFileSSL) then
 begin
 {$IFDEF UNIX}
 IdOpenSSLSetLoadSymLinksFirst(False);
 {$ENDIF}
 IdServerIOHandlerSSLOpenSSL.SSLOptions.CertFile := aFileSSL;
 IdServerIOHandlerSSLOpenSSL.SSLOptions.KeyFile := aFileSSL;
 IdServerIOHandlerSSLOpenSSL.SSLOptions.RootCertFile := aFileSSL;
 IdHTTPServer.IOHandler := IdServerIOHandlerSSLOpenSSL;
 end;
```
PS: I will check the function `WhichFailedToLoad()` a little later, there is no way yet.

**Comment by rlebeau** [comment]
The only notable change made to Indy's OpenSSL code in the past year is that the `IdSSLOpenSSLHeaders.Load()` function was updated a few months ago, so that if OpenSSL 1.1+ binaries were loaded into memory then `Load()` would fail and `WhichFailedToLoad()` would report `'Unsupported SSL Library version'`.

**Comment by jonyrh** [comment]
If use `IdOpenSSLSetLoadSymLinksFirst(True); ` then error `is loading libcrypto in an unsafe way`. 
if  `IdOpenSSLSetLoadSymLinksFirst(False); IdSSLOpenSSLHeaders.Load();`
out "Unsupported SSL Library version: 20000000."

**Comment by jonyrh** [comment]
`IdSSLOpenSSL.OpenSSLVersion()` out `OpenSSLVersion LibreSSL 2.8.3`
`SSLeay536870912` out as string `536870912`
`WhichFailedToLoad()` out `Unsupported SSL Library version: 20000000.`

**Comment by rlebeau** [comment]
Well, there you go then.  Indy doesn't know anything about LibreSSL, so it doesn't know you are using LibreSSL instead of OpenSSL. It just looks at the version number being reported by `libcrypto` and thinks you are trying to load OpenSSL 2.0.0, which is why it fails to load now.  If LibreSSL 2.8.3 is backwards compatible with OpenSSL 1.0.2, I will have to put in an explicit check for that version to allow it to load.

**Comment by rlebeau** [comment]
I have checked in an update to have `IdSSLOpenSSLHeaders.Load()` allow LibreSSL to load.  Just waiting for Lazarus' OPM to get the update.

**Comment by jonyrh** [comment]
Thank you very much! Everything is working! You are super!
