### ISSUE TITLE
UTCOffsetToStr from IdGlobal (OPM 10.6.2.4060) - wrong UTC meaning negative/positive FPC3.2.0 Lazarus 2.0.12 Win64/Linux64/macOS64

### ISSUE THREAD

**Issue by jonyrh** [IndySockets/Indy#396]
`UTCOffsetToStr` from `IdGlobal` (OPM 10.6.2.4060) - wrong UTC meaning negative/positive FPC3.2.0 Lazarus 2.0.12 Win64/Linux64/macOS64

`UTCOffsetToStr` - allways return inverse UTC negative/positive meaning. 
tested in:
Windows Server 2008 R2 x64
Windows 10 x64
Windows 11 x64
ununtu 16.04 x64
ununtu 20.04 x64
macOS 12.1 21C52

I use a crutch:
```
IdMessage.UseNowForDate:=False; 
IdMessage.Date:= IncMinute(Now, GetLocalTimeOffset*2);
```

Simple code for see header `Date`:
```
var
  ms: TMemoryStream;
begin
  IdMessage1.Clear;
  IdMessage1.Recipients.EMailAddresses:='1@1.ru';
  IdMessage1.From.Name:='jonyrh';
  IdMessage1.From.Address:='1@1.ru';
  ms:= TMemoryStream.Create;
  IdMessage1.SaveToStream(ms);
  ms.Position:=0;
  Memo1.Lines.LoadFromStream(ms);
  ms.Free; 
end;
```

function:
```
unction UTCOffsetToStr(const AOffset: TDateTime; const AUseGMTStr: Boolean = False): string;
var
  AHour, AMin, ASec, AMSec: Word;
  s: string;
  {$IFDEF STRING_IS_IMMUTABLE}
  LSB: TIdStringBuilder;
  {$ENDIF}
begin
  if (AOffset = 0.0) and AUseGMTStr then
  begin
    Result := 'GMT'; {do not localize}
  end else
  begin
    DecodeTime(AOffset, AHour, AMin, ASec, AMSec);
    s := IndyFormat(' %0.2d%0.2d', [AHour, AMin]); {do not localize}
    {$IFDEF STRING_IS_IMMUTABLE}
    LSB := TIdStringBuilder.Create(5);
    LSB.Append(s);
    if AOffset < 0.0 then begin
      LSB[0] := '-'; {do not localize}
    end else begin
      LSB[0] := '+'; {do not localize}
    end;
    Result := LSB.ToString;
    {$ELSE}
    Result := s;
    if AOffset < 0.0 then begin
      Result[1] := '-'; {do not localize} - WRONG RESULT, IF SET RESULT '+' THEN HEADER IdMessage "Date" IS REAL
    end else begin
      Result[1] := '+'; {do not localize} - WRONG RESULT,  IF SET RESULT '-' THEN HEADER IdMessage "Date" IS REAL
    end;
    {$ENDIF}
  end;
end;   
```

My UTC +05:00, `GetLocalTimeOffset` = -300
If NO change Result in function then Result = `Date:` Tue, 11 Jan 2022 10:49:28 -0500 - WRONG, NOT +
If change Result in function then Result = `Date:` Tue, 11 Jan 2022 10:49:28 +0500 - NORMAL

**Comment by rlebeau** [comment]
There is no problem with `UTCOffsetToStr()` itself.  It is supposed to output `'-'` for a negative offset and `'+'` for a positive offset.  This has been working fine for years.  The real problem is more likely to be that the `TDateTime` being passed in to `UTCOffsetToStr()` is using a reversed sign to begin with, for instance if there is a logic bug in `OffsetFromUTC()` (which does have questional logic on some platforms).  FYI, `OffsetFromUTC()` is nearing *deprecated* status in leau of new functions recently added like `LocalTimeToUTCTime()`/`UTCTimeToLocalTime()`. There are only a few spots remaining in Indy where `OffsetFromUTC()` is still being used.

In your example, the value of the `TIdMessage.Date` is expected to be expressed in *local* time, so incrementing it by `GetLocalTimeOffset` is just plain wrong. You should be using simply `IdMessage.Date := Now;` or `IdMessage.UseNowForDate := True;`, as internally `TIdMessage` uses `LocalDateTimeToGMT()` when creating the email's `Date` header:

```
FLastGeneratedHeaders.Values['Date'] := LocalDateTimeToGMT(LDate); {do not localize}
```

And `LocalDateTimeToGMT()` happens to be one of the few remaining spots that is still using `OffsetFromUTC()` (for input to `UTCOffsetToStr()`!):

```
function LocalDateTimeToGMT(const Value: TDateTime; const AUseGMTStr: Boolean = False) : String;
var
  wDay, wMonth, wYear: Word;
begin
  DecodeDate(Value, wYear, wMonth, wDay);
  Result := IndyFormat('%s, %d %s %d %s %s',    {do not localize}
                   [wdays[DayOfWeek(Value)], wDay, monthnames[wMonth],
                    wYear, FormatDateTime('HH":"nn":"ss', Value), {do not localize}
                    UTCOffsetToStr(OffsetFromUTC, AUseGMTStr)]);
end;
```

So, I would suggest checking the output of `OffsetFromUTC()` on your system and see if it is being reversed incorrectly.

**Comment by jonyrh** [comment]
Thenks, i try `OffsetFromUTC()` , but how it help me, if `IdMessage` generate heading time? Alwayse using a crutch?

```
var
  n: Int64;
begin
  n:= Round(OffsetFromUTC * SecsPerDay / 60) ;
  showmessage(n.ToString);
```
Results:
Win11 x64 = -300
Win10 x64 = -300
Win Server 2008 R2 = -300

![image](https://user-images.githubusercontent.com/28771126/149615333-ab36b3f6-dce3-49a6-b766-036b63197dcd.png)
![image](https://user-images.githubusercontent.com/28771126/149615342-f6b656ff-51d2-4043-a550-30aad3e0bcdb.png)
![image](https://user-images.githubusercontent.com/28771126/149615355-b77005dd-260c-4263-9aad-5c85264810e8.png)

**Comment by rlebeau** [comment]
The return value of `OffsetFromUTC()` is meant to be **subtracted** from local time to get UTC time, and to be **added** to UTC time to get local time.  Since your time zone is `UTC+05:00`, `OffsetFromUTC()` *should* return a `TDateTime` representing +300 minutes:

local time - (+300)mins = local time - 300mins = UTC time
UTC time + (+300)mins = UTC time + 300mins = local time

Thus, `UTCOffsetToStr(OffsetToUTC())` *would* return `'UTC+05:00'`, as expected.

But, in your case, `OffsetFromUTC()` is returning a `TDateTime` representing -300 minutes instead.  Under FPC, `OffsetFromUTC()` simple calls FPC's [`GetLocalTimeOffset()`](https://www.freepascal.org/docs-html/rtl/sysutils/getlocaltimeoffset.html) function and then returns its return value *as-is* in `TDateTime` format.  The sign is preserved. 

According to `GetLocalTimeOffset()`'s documentation, its return value is meant to be **added** to local time, not **subtracted**.  Thus, it makes sense that it would return -300 in your case.  I was not aware of that fact before.  So, the proper fix would be to update `OffsetFromUTC()` to flip the sign on `GetLocalTimeOffset()`'s return value.  I will checkin such a fix shortly.

---

FYI, on a side note, the RTL has a `MinsPerDay` constant:

`n := Round(OffsetFromUTC * MinsPerDay);`

**Comment by jonyrh** [comment]
Thank you very much, you are great as always!
