### ISSUE TITLE
leaks reported by fpcx64mm while using indy for TMS MQTT

### ISSUE THREAD

**Issue by dkounal** [IndySockets/Indy#461]
Hi 
Trying to use TMS MQTT 2.0 in FPC 3.2.3 x86_64-win64 I was getting a 217 error during program's exit. 
Sysutils is my first unit in uses main pas file. My program seems to work with exception while finishing and no leaks reported by both fastmm4/5.
Just because I do not have such problems when compiled in 32bit Delphi, I used the fpcx64mm that provides more information and I got the following. At least TIdThreadSafeInteger and TIdCriticalSection are from Indy and this 217 error starts by adding the unit with the MQTT that uses the indy components.

WARNING! THIS PROGRAM LEAKS MEMORY!
Memory Status:
 Small:  8/448B  including tiny<=128B arenas=8 fed from Medium
 Medium: 5MB/6MB    peak=6MB current=4 alloc=5 free=1 sleep=0
 Large:  0B/0B    peak=0B current=0 alloc=0 free=0 sleep=0
 Small Blocks since beginning: 454K/15MB (as small=43/46 tiny=56/56)
  32=439K  48=7K  64=2K  128=796  96=683  80=648  112=597  352=492
 Small Blocks current: 8/448B
  48=3  64=2  32=2  112=1
Leaks Identified:
 small block leak x1 of size=48  (getmem=984 freemem=983)
 small block leak x2 of size=48  (getmem=971 freemem=969)
 small block leak x1 of size=32  (getmem=56192 freemem=56191)
 small block leak x1 of size=32  (getmem=56196 freemem=56195)
 small block leak x1 of size=64  (getmem=282 freemem=281)
 small block leak x1 of size=112  (getmem=74 freemem=73)
 small block leak x1 of size=64  (getmem=272 freemem=271)
 Total small block leaks = 8
 probable TFaultControl leak (96/112 bytes) at $0000000005FEBAF0
 probable TIdThreadSafeInteger leak (24/32 bytes) at $0000000005E6D160
 probable TUTF8Encoding leak (32/48 bytes) at $0000000005EF8860
 probable TMBCSEncoding leak (32/48 bytes) at $0000000005EFBC30
 probable TValueInteger leak (40/48 bytes) at $0000000005EFF9B0
 probable TIdCriticalSection leak (48/64 bytes) at $0000000005F1E620
 probable TIdCriticalSection leak (48/64 bytes) at $0000000005F3B6E0
 Total objects leaks = 7

**Comment by dkounal** [comment]
Just to mention that idSSLOpenSSL.pas , IdComponent, IdTCPClient, IdTCPConnection, IdGlobal,   IdContext,  IdIOHandlerSocket, IdIPAddress are used by TMS MQTT

**Comment by rlebeau** [comment]
The `TIdThreadSafeInteger` and `TIdCriticalSection` leaks are expected and intentional.  See the comments regarding `FREE_ON_FINAL` in the `initialization`/`finalization` sections of the `IdThread.pas` and `IdStack.pas` units.

`FREE_ON_FINAL` is not defined by default, and so these expected leaks are registered with the memory manager so they are not included in leak reports - at least, on systems that support this feature, which unfortunately [does not include FPC](https://forum.lazarus.freepascal.org/index.php?topic=32452.0) at this time (see the `REGISTER_EXPECTED_MEMORY_LEAK` and `HAS_System_RegisterExpectedMemoryLeak` defines in `IdCompilerDefines.inc`).

Ignoring expected leaks works only on Delphi versions that have [`System.RegisterExpectedMemoryLeak()`](https://docwiki.embarcadero.com/Libraries/en/System.RegisterExpectedMemoryLeak), or which have re-compiled Indy to use FastMM, MadExcept, or LeakCheck libraries directly. 

The est of the leaks reported are not related to Indy.

**Comment by dkounal** [comment]
Thanks a lot Remy. 
I read the comments in the code. 
the 217 error was due to my code with threads and it is fixed now. But it help to learn better indy.
